/**
 * @file system_event.h
 * @brief Generic event type that flows through the entire system.
 *
 * ARCHITECTURAL MANDATE: This is the ONLY inter-layer data contract.
 * The HAL produces events of this type; the Dispatcher routes them;
 * the FSM and Safety Monitor consume them.  No layer above the HAL
 * ever references UART frames, GPIO pin numbers, or any peripheral detail.
 *
 * All queue transfers copy the full struct (pass-by-value) to prevent
 * dangling-pointer hazards (NFR-2, NFR-6).
 */

#ifndef SYSTEM_EVENT_H
#define SYSTEM_EVENT_H

#include <stdint.h>

/* ---------------------------------------------------------------------------
 * Event Types
 * --------------------------------------------------------------------------- */
typedef enum {
    /* --- Command events (from Supervisor → HAL → Dispatcher → FSM) --- */
    EVT_CMD_OPEN            = 0x01,  /**< Normal open request.              */
    EVT_CMD_CLOSE           = 0x02,  /**< Normal close request.             */
    EVT_CMD_EMERGENCY_OPEN  = 0x03,  /**< Emergency open; highest priority. */
    EVT_CMD_RESET           = 0x04,  /**< Explicit fault-reset command.     */

    /* --- Sensor events (HAL-debounced before dispatch) --- */
    EVT_SENSOR_FULLY_OPEN   = 0x10,  /**< Limit switch: door is fully open. */
    EVT_SENSOR_FULLY_CLOSED = 0x11,  /**< Limit switch: door is fully closed.*/
    EVT_OBSTRUCTION_DETECTED= 0x12,  /**< Obstruction sensor asserted.      */
    EVT_OBSTRUCTION_CLEAR   = 0x13,  /**< Obstruction sensor de-asserted (SR-1). */

    /* --- Internal / system events --- */
    EVT_COMM_TIMEOUT        = 0x20,  /**< No valid frame in COMM_TIMEOUT_MS. */
    EVT_MOTOR_STALL         = 0x21,  /**< FSM stall timeout expired (SR-7). */
    EVT_SPOF_DETECTED       = 0x22,  /**< Contradictory sensor data (SR-3). */
    EVT_HOMING_COMPLETE     = 0x23,  /**< Homing routine finished (SR-4).   */
    EVT_FAULT_PERSIST       = 0x24,  /**< NVS fault found on boot (SR-4).   */
    EVT_HEARTBEAT           = 0x25,  /**< Periodic watchdog/heartbeat.      */

    EVT_UNKNOWN             = 0xFF,  /**< Parse error / unrecognised frame. */
} event_type_t;

/* ---------------------------------------------------------------------------
 * Event Source — for audit logging (NFR-4)
 * --------------------------------------------------------------------------- */
typedef enum {
    SRC_UART_SUPERVISOR = 0,  /**< Arrived via UART from Python Supervisor. */
    SRC_INTERNAL_FSM    = 1,  /**< Generated internally by FSM logic.       */
    SRC_INTERNAL_SAFETY = 2,  /**< Generated by Safety Monitor.             */
    SRC_HAL_SENSOR      = 3,  /**< Generated by HAL sensor debouncer.       */
} event_source_t;

/* ---------------------------------------------------------------------------
 * Generic Event Struct
 * Copied by value through FreeRTOS queues — no pointers to volatile memory.
 * --------------------------------------------------------------------------- */
typedef struct {
    event_type_t   type;        /**< What happened.                          */
    event_source_t source;      /**< Where it came from (audit trail).       */
    uint32_t       timestamp_ms;/**< esp_timer_get_time() / 1000, ms since boot. */
    uint32_t       payload;     /**< Optional numeric payload (e.g. sensor value). */
} system_event_t;

#endif /* SYSTEM_EVENT_H */